// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcBqrWyW6PDSPGAimULWoHCJtQ9DC0b0o',
    appId: '1:960760441947:web:14a2774a26300d6837a37e',
    messagingSenderId: '960760441947',
    projectId: 'flutter-chat-app-demo3',
    authDomain: 'flutter-chat-app-demo3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-demo3.appspot.com',
    measurementId: 'G-JB3CZ2QRWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvR6d2KI--KcOHy7coy7kPDOs-Gxhjtrg',
    appId: '1:960760441947:android:14aded1a0658041137a37e',
    messagingSenderId: '960760441947',
    projectId: 'flutter-chat-app-demo3',
    storageBucket: 'flutter-chat-app-demo3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh86tOjvW0jxpBq3u-iP2elkh6M_5TkAY',
    appId: '1:960760441947:ios:ad18a7ad33bc504237a37e',
    messagingSenderId: '960760441947',
    projectId: 'flutter-chat-app-demo3',
    storageBucket: 'flutter-chat-app-demo3.appspot.com',
    iosClientId: '960760441947-qolmbtq9itojv5oug4p4nqt9954sarvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppDemo3',
  );
}
